language: node_js
node_js:
- '5'
env:
  global:
  - secure: SKGcJY2VC2saVLzVe26aBDF6xifmH23cgZigabH/7F+gN1x984kkaIVItcj4PiZv/0BviASkvBpEJ5StRJGFyQwUMlDh47fkCm8K6UMSN+zUaow25Xg8whC7cFRC6Gm7p5s8iWz78OhSTLOUGchZ5hFiJQj/Hh1iuFiGO+uQr3rmTQEG4BuQqCYFkKphv3fN8LhzAGPbWe+F5Fa2HCAddclKtgNfqO2G2FSDohXLknYmFtdCE/1PS27Miy7LrNYAjDEHdzV+CoyHPDy4F1hKBNF0tQYzfa3ib8BMN0OEJHEyvGFhbJWdGOHetYXQZj5TZIfWVs+d8gfL3gbz1IR7GOB8STRvOLxkMiUDMpdxiZE9R8exuCUOtJLtPUD3STG/tcu1TZQewouSOWvY1tWHjPOOgDVo8NoKtaqhphUf65XsZ522vfmeuDQEOeidkc1U+6Z1DmdrMqrhlLoBlQs1czoUA3hR0E2PIgeS2VS7bVtII3X2VOgMquILENcezlyOTqcNjNYHxb+cPldDUo8M8yaJMo3G9RuLBjRA0Vzzfa6pw/LKIXeFsjMYPhC/Zl8XwKdZPtSsNzJpnLYReW5hazAjwO/laMNhxsvHIcPi3BXX+6/Zwg+A6QKffKlYuSNMFU7zud7Is4PDOSt7ChhdaFUwBk/bJ0xB8XNJTqlSiyo=
  - SOURCEDB_HOST: mysql-db.cnltbg2tkrfl.eu-central-1.rds.amazonaws.com/
  - SOURCEDB_USER: devseed
  - SOURCEDB_DB: evidence_action_db
  - secure: TtFt1V7RaxaiPEkXytCVHywnoHMKHKHejry9N/msr//FuQh14lknl6V7Njp5RjKFWgLYY7mt3fnlaQ30xsuI9HPngaiudKxSwi7ARnTTRK6pBWoDrf9mmcB6y4yemFKn/jKB1bEz8CR2JN3JwQt6jGq21uZ9q5ydt5307VMbSzrco5z01lQuAeik86Fx3riWtznCJF76EK4sX+vpc3JgkX4n1jSr/AqJGVuT+byrmlQbVr1XDSxAJ7oXLIphLdnXkoFvWd1X1ZZaOLcUZ/uABZPBxHb4sM8a6zM5KGwDwz8GOy2gZRFFJpuZ6JQs9HB18KlXnCcrYKVOVhyavC+TdJvmQQ/6qb4krzMkf56tOjhImP+QaGKVGpjaBRHLQHMxr8cl0R0PV0n/WqvF571ogES20UlvMIetT3eEe5CgZ5V3h48Ep1jPr+I4klaLicBteQMvN28McVXyrtLx3LhwlFbAi0aPEHMWN4F6FCD0qY8L7/oRPp5r1+chCJTA3Tn4Bk/cHOEQya0wOTcE/tufM9Myk+8LHuS+GILbCTVqoa+MZ5pS2Fp2zIwqB6aJwmpY8fSR4ewT4wWxAsj1sQezAh3DjiZfspY0/BV8bbD5zPu2EMtlJqOtvwrbMDii7xJ75ME/DTLZJVwwstJYK2biCD1Md5QC+csyRm01CeFpbWE=
before_script:
- npm test
script:
- npm run worker
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: GmwZO/APM4WY0QVfGSVCGATrRHhFi32NLf4T+744CZGwRZhzhdKquizszU5n6hMWfXPbBxzefUZyMQ035ibEtaZz2I56rnhXrJHp9ehoXtthrAsC4nXa0Uq0dRnU2wsmG/kB4CMO2X1hg/ptS/OWB3j48C+NmtE1nJzgfyeN6lUa7m7UJvujpSqj0nxUS/aZo0hj8Jilsyp+2RTxTgkO6u6qToKfNJBDJK1Q5SdFn5NZo5o5QvJlMBxt8xg0YfRxpFuiTChB7WlZVFuw4QzStdwXfNZTn70USnP+9wr1Kw4y07Y4f2DEFA3FKlWoP+yLEsR9LS2mUfKeI1MmtHZjSf7LGNSprS5BK5qWW6Hdnn9DwydmgNxfJ9sWnRVG5IyujrGWGYmsd+EhdVUus36sVdGvObbnjraKU69jbpaSSNeu1PpIYCOeXaVXiEhhpWdorOm4+pWROVG8r4VE0QmTaLpoGxoWYKzqeDEgHd+1yCEp4j1/NZmTdtxF68wRv4ZXkTuvyoJmUKie7rDWbWJa5HrXYTELjjYI4jPD951n6PAYNAI9CMc6DWya4RPRMs6dqoTigud96gyFOgU7t5TNi/mIfimvQ8TWWXFE/SkpP1u3RUOyyye4qt63SA4yUSMNvEi3lVZFBLxGaLtsSri2yjyhJ0Z52n9mYiHz5kAF+Fw=
  app: dispenserdata-api
  on:
    repo: evidenceaction/Dispensers-Dashboard-API
