language: node_js
node_js:
- '5'
env:
  global:
  - SOURCEDB_HOST: mysql-db.cnltbg2tkrfl.eu-central-1.rds.amazonaws.com
  - SOURCEDB_USER: devseed
  - SOURCEDB_DB: evidence_action_dsw
  - secure: "Pe3Iq3alET+Nz74LF8p2tFHtfNxITH1/uLIU87LIEcFFnmZxT1B4hQpU5cZs5ObD8DfjAkRfZtx5D9clfv5/+MfY5TyhAUMFeZjtubRUJSGK99Y2Qj7DjPJHueLEuR7SSMwHT1TFkp8VahI+9vjWbNfF1X5UPbqlN8uvIWVXxArGYbDC6ODOBsSOPU+Efrg+p3evOeAQd0pukxn/YDNtioquPcATeeP5hxSK5pPj22U0QzHyqrM/W9BczUADwd0NOfK1xUR0YbVFJpH95O3ywjRWzd9itvd/mw4tWrvarVF0RvbxWLbyGpgSqobeKpWVlJXCDiREV+UaWhV8EL7FaMRxDGcDb57JbwYCEBpSIuFWk6FrCTyqyvbJ3L+vs5mrSq0EPd/pC8Rkxt9iwmsCRPP2tSKF6AvCgEBlckEwDRFHaRALVxEG7n7CziwruuZqN08lHLu6VPJez+uJ6cXXyPOO1e962Fir5OesKuDOIvUvYrGaqUfUzsNllosIc/1FltNadePb74NzKFvbR0tjaVSmJg3FRQkUIPBhUtYFXmAGO56DMsz37So6dJIXUf3Jin9eetOG6ZmQthmWmpMtQwWhIdIhlQj85k0Y7OjnQdK6UDzrctB3DjHlCwPp0L9ChYSD9277ixzoDlMD+vUqxi1oVOH0fO+xNQ78WI2sZbY="
before_script:
- npm test
script:
- npm run worker
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: GmwZO/APM4WY0QVfGSVCGATrRHhFi32NLf4T+744CZGwRZhzhdKquizszU5n6hMWfXPbBxzefUZyMQ035ibEtaZz2I56rnhXrJHp9ehoXtthrAsC4nXa0Uq0dRnU2wsmG/kB4CMO2X1hg/ptS/OWB3j48C+NmtE1nJzgfyeN6lUa7m7UJvujpSqj0nxUS/aZo0hj8Jilsyp+2RTxTgkO6u6qToKfNJBDJK1Q5SdFn5NZo5o5QvJlMBxt8xg0YfRxpFuiTChB7WlZVFuw4QzStdwXfNZTn70USnP+9wr1Kw4y07Y4f2DEFA3FKlWoP+yLEsR9LS2mUfKeI1MmtHZjSf7LGNSprS5BK5qWW6Hdnn9DwydmgNxfJ9sWnRVG5IyujrGWGYmsd+EhdVUus36sVdGvObbnjraKU69jbpaSSNeu1PpIYCOeXaVXiEhhpWdorOm4+pWROVG8r4VE0QmTaLpoGxoWYKzqeDEgHd+1yCEp4j1/NZmTdtxF68wRv4ZXkTuvyoJmUKie7rDWbWJa5HrXYTELjjYI4jPD951n6PAYNAI9CMc6DWya4RPRMs6dqoTigud96gyFOgU7t5TNi/mIfimvQ8TWWXFE/SkpP1u3RUOyyye4qt63SA4yUSMNvEi3lVZFBLxGaLtsSri2yjyhJ0Z52n9mYiHz5kAF+Fw=
  app: dispenserdata-api
  on:
    repo: evidenceaction/Dispensers-Dashboard-API
