language: node_js
node_js:
- '5'
env:
  global:
  - secure: SKGcJY2VC2saVLzVe26aBDF6xifmH23cgZigabH/7F+gN1x984kkaIVItcj4PiZv/0BviASkvBpEJ5StRJGFyQwUMlDh47fkCm8K6UMSN+zUaow25Xg8whC7cFRC6Gm7p5s8iWz78OhSTLOUGchZ5hFiJQj/Hh1iuFiGO+uQr3rmTQEG4BuQqCYFkKphv3fN8LhzAGPbWe+F5Fa2HCAddclKtgNfqO2G2FSDohXLknYmFtdCE/1PS27Miy7LrNYAjDEHdzV+CoyHPDy4F1hKBNF0tQYzfa3ib8BMN0OEJHEyvGFhbJWdGOHetYXQZj5TZIfWVs+d8gfL3gbz1IR7GOB8STRvOLxkMiUDMpdxiZE9R8exuCUOtJLtPUD3STG/tcu1TZQewouSOWvY1tWHjPOOgDVo8NoKtaqhphUf65XsZ522vfmeuDQEOeidkc1U+6Z1DmdrMqrhlLoBlQs1czoUA3hR0E2PIgeS2VS7bVtII3X2VOgMquILENcezlyOTqcNjNYHxb+cPldDUo8M8yaJMo3G9RuLBjRA0Vzzfa6pw/LKIXeFsjMYPhC/Zl8XwKdZPtSsNzJpnLYReW5hazAjwO/laMNhxsvHIcPi3BXX+6/Zwg+A6QKffKlYuSNMFU7zud7Is4PDOSt7ChhdaFUwBk/bJ0xB8XNJTqlSiyo=
  - SOURCEDB_HOST: 64.91.229.62
  - SOURCEDB_USER: devseed
  - SOURCEDB_DB: evidence_action_dsw
  - secure: afHRnMFz8XArmwIbttN3NbbY8HRMbuFi4bSZ6tvp2elPKkNyPkiYuIef/RKVqyIA/mLxn/JdIbS0syLTGXTvLF/B9MA6dqfXE1cdLbHGpFkW5N1ZNNPPz4038gmPTgNnt9J2XQA5pB/lSmuMI2d+BBqtl6kUEe3b5omMQwkNhovHggTxbrfFM9LjcBIdb8BhlyB1tYhbThUTC3Bo+chZ08TQWcf5g67fBQyG3K6T3BB9Fqw3/RKMxV5rd0vcs3aoF7nk+JgMqHL28TwHv7rMNxcczggDIMgmOG/MHnQMNn7uHxN4qd2s1CudRnFkEPWv8GPOerGLAOECOC47QYG4rDjuFwYeR0gyXDawmQK5IbixIJD2nRl/zHLgtUZbLHQjWUuxVJQL7eUKq1Apai0BCjB3brm3/xCnpg7Nu2gM34e5pyx3k1f5N/3MjezXDhWlNw3JDxCWmQBjtbCdBq/A68DD6wWp8vNxdqMdJuShEQkx1ihw7BEclaZkVDAkjLsuxCvNjQIxVc1fU2ntQAxF0t85BX1wKErCa+k28FTjN/wecfuEWh/R5++LbrivwRwjkOjcxaPA3IxFiffBwVy9lZvR50fZNOiAubJM2tkZiPiq6+s2VZa9IZocvr7IJnvrzBrcZ0QucRFMZT4zFcBYiAFgA/82KA6YpQUP2JSs8HM=
before_script:
- npm test
script:
- npm run worker
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: GmwZO/APM4WY0QVfGSVCGATrRHhFi32NLf4T+744CZGwRZhzhdKquizszU5n6hMWfXPbBxzefUZyMQ035ibEtaZz2I56rnhXrJHp9ehoXtthrAsC4nXa0Uq0dRnU2wsmG/kB4CMO2X1hg/ptS/OWB3j48C+NmtE1nJzgfyeN6lUa7m7UJvujpSqj0nxUS/aZo0hj8Jilsyp+2RTxTgkO6u6qToKfNJBDJK1Q5SdFn5NZo5o5QvJlMBxt8xg0YfRxpFuiTChB7WlZVFuw4QzStdwXfNZTn70USnP+9wr1Kw4y07Y4f2DEFA3FKlWoP+yLEsR9LS2mUfKeI1MmtHZjSf7LGNSprS5BK5qWW6Hdnn9DwydmgNxfJ9sWnRVG5IyujrGWGYmsd+EhdVUus36sVdGvObbnjraKU69jbpaSSNeu1PpIYCOeXaVXiEhhpWdorOm4+pWROVG8r4VE0QmTaLpoGxoWYKzqeDEgHd+1yCEp4j1/NZmTdtxF68wRv4ZXkTuvyoJmUKie7rDWbWJa5HrXYTELjjYI4jPD951n6PAYNAI9CMc6DWya4RPRMs6dqoTigud96gyFOgU7t5TNi/mIfimvQ8TWWXFE/SkpP1u3RUOyyye4qt63SA4yUSMNvEi3lVZFBLxGaLtsSri2yjyhJ0Z52n9mYiHz5kAF+Fw=
  app: dispenserdata-api
  on:
    repo: evidenceaction/Dispensers-Dashboard-API
