language: node_js
node_js:
- '5'
env:
  global:
  - secure: SKGcJY2VC2saVLzVe26aBDF6xifmH23cgZigabH/7F+gN1x984kkaIVItcj4PiZv/0BviASkvBpEJ5StRJGFyQwUMlDh47fkCm8K6UMSN+zUaow25Xg8whC7cFRC6Gm7p5s8iWz78OhSTLOUGchZ5hFiJQj/Hh1iuFiGO+uQr3rmTQEG4BuQqCYFkKphv3fN8LhzAGPbWe+F5Fa2HCAddclKtgNfqO2G2FSDohXLknYmFtdCE/1PS27Miy7LrNYAjDEHdzV+CoyHPDy4F1hKBNF0tQYzfa3ib8BMN0OEJHEyvGFhbJWdGOHetYXQZj5TZIfWVs+d8gfL3gbz1IR7GOB8STRvOLxkMiUDMpdxiZE9R8exuCUOtJLtPUD3STG/tcu1TZQewouSOWvY1tWHjPOOgDVo8NoKtaqhphUf65XsZ522vfmeuDQEOeidkc1U+6Z1DmdrMqrhlLoBlQs1czoUA3hR0E2PIgeS2VS7bVtII3X2VOgMquILENcezlyOTqcNjNYHxb+cPldDUo8M8yaJMo3G9RuLBjRA0Vzzfa6pw/LKIXeFsjMYPhC/Zl8XwKdZPtSsNzJpnLYReW5hazAjwO/laMNhxsvHIcPi3BXX+6/Zwg+A6QKffKlYuSNMFU7zud7Is4PDOSt7ChhdaFUwBk/bJ0xB8XNJTqlSiyo=
  - SOURCEDB_HOST: 64.91.229.62
  - SOURCEDB_USER: devseed
  - SOURCEDB_DB: evidence_action_dsw
  - secure: afHRnMFz8XArmwIbttN3NbbY8HRMbuFi4bSZ6tvp2elPKkNyPkiYuIef/RKVqyIA/mLxn/JdIbS0syLTGXTvLF/B9MA6dqfXE1cdLbHGpFkW5N1ZNNPPz4038gmPTgNnt9J2XQA5pB/lSmuMI2d+BBqtl6kUEe3b5omMQwkNhovHggTxbrfFM9LjcBIdb8BhlyB1tYhbThUTC3Bo+chZ08TQWcf5g67fBQyG3K6T3BB9Fqw3/RKMxV5rd0vcs3aoF7nk+JgMqHL28TwHv7rMNxcczggDIMgmOG/MHnQMNn7uHxN4qd2s1CudRnFkEPWv8GPOerGLAOECOC47QYG4rDjuFwYeR0gyXDawmQK5IbixIJD2nRl/zHLgtUZbLHQjWUuxVJQL7eUKq1Apai0BCjB3brm3/xCnpg7Nu2gM34e5pyx3k1f5N/3MjezXDhWlNw3JDxCWmQBjtbCdBq/A68DD6wWp8vNxdqMdJuShEQkx1ihw7BEclaZkVDAkjLsuxCvNjQIxVc1fU2ntQAxF0t85BX1wKErCa+k28FTjN/wecfuEWh/R5++LbrivwRwjkOjcxaPA3IxFiffBwVy9lZvR50fZNOiAubJM2tkZiPiq6+s2VZa9IZocvr7IJnvrzBrcZ0QucRFMZT4zFcBYiAFgA/82KA6YpQUP2JSs8HM=
before_script:
- npm test
script:
- npm run worker
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: X4j8891D8cF2+Ut3Ek3jx14jiwG7njDoNqJ5rcg9PVNFHAAdoYqf8Ao2ADggpWV3769Qloy+T5tJ9+5cS+TRcSpU+7TgyB0X3sVqNeElgvEhqR/87h1GlbHwz4nU4KayhDvmQwbb8/dykZonYbBKKmtcPfdG4jPTx/3heA/7i+HtGw9saNemV1QWeoiLSQFNU6MW6L2lRhxaYLgJLPGw6ST6eXEPuRzfZ7qOhtI+Ul54JkUEUPimp/7FJ1ZAa0W8NYkkdryFUYnvZXdqGOpcAmLs+r3ZsE604f4BQW4r5PKEmJWbcp9w69AjgUSwuIpwmoS98UuHGysExOmQQmwryEDfHS8mrHIwit17Df6CiTEP3qmDBIvOzWRi4DXl9Dm427KFD8b/jykz3b9wV7J2VmqKamMsiublJX6z8dwtB5F4YaXNWAa51wLiU3B6k4YEtsdHqXeEfujVNNGLarNo9WcWuTcPIuZv8PlRe1OFniox9+mWx7+tTpZ3RaUKNHjBO6RIW/WzzFh1L8TXU1uDjsQWceQXfciP5+kib9DYHXGYWgRq3N0NBp71D/p1FiKjz/tlwumgSh4JjXNJLRC7dqfY9onf/+4PYr90/EOzd51wsbXhuG7YXvHOmE97wWWU9f1KYintR+8NiRoJC61OhIEvMMeVWGEvI575AJv19Qg=
  app: dsw-staging
  on:
    repo: developmentseed/safe-water-api
